"""fix unique indexes and add missing ones

Revision ID: 97bff57edc6f
Revises: 0001
Create Date: 2026-04-24 19:53:23.891268

"""
from typing import Sequence, Union
from alembic import op

revision: str = '97bff57edc6f'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.drop_constraint(op.f('categories_slug_key'), 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_domain_events_aggregate_type'), 'domain_events', ['aggregate_type'], unique=False)
    op.drop_constraint(op.f('orders_number_key'), 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_number'), table_name='orders')
    op.create_index(op.f('ix_orders_number'), 'orders', ['number'], unique=True)
    op.drop_constraint(op.f('pages_slug_key'), 'pages', type_='unique')
    op.drop_index(op.f('ix_pages_slug'), table_name='pages')
    op.create_index(op.f('ix_pages_slug'), 'pages', ['slug'], unique=True)
    op.drop_constraint(op.f('product_variants_sku_key'), 'product_variants', type_='unique')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.drop_constraint(op.f('products_slug_key'), 'products', type_='unique')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.drop_constraint(op.f('sessions_token_hash_key'), 'sessions', type_='unique')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.drop_constraint(op.f('shipments_tracking_number_key'), 'shipments', type_='unique')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.drop_constraint(op.f('staff_users_email_key'), 'staff_users', type_='unique')
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=True)
    op.drop_constraint(op.f('stock_levels_variant_id_key'), 'stock_levels', type_='unique')
    op.drop_index(op.f('ix_stock_levels_variant_id'), table_name='stock_levels')
    op.create_index(op.f('ix_stock_levels_variant_id'), 'stock_levels', ['variant_id'], unique=True)
    op.drop_constraint(op.f('support_tickets_number_key'), 'support_tickets', type_='unique')
    op.drop_index(op.f('ix_support_tickets_number'), table_name='support_tickets')
    op.create_index(op.f('ix_support_tickets_number'), 'support_tickets', ['number'], unique=True)
    op.create_index(op.f('ix_support_tickets_order_id'), 'support_tickets', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_order_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_number'), table_name='support_tickets')
    op.create_index(op.f('ix_support_tickets_number'), 'support_tickets', ['number'], unique=False)
    op.create_unique_constraint(op.f('support_tickets_number_key'), 'support_tickets', ['number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_stock_levels_variant_id'), table_name='stock_levels')
    op.create_index(op.f('ix_stock_levels_variant_id'), 'stock_levels', ['variant_id'], unique=False)
    op.create_unique_constraint(op.f('stock_levels_variant_id_key'), 'stock_levels', ['variant_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('staff_users_email_key'), 'staff_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=False)
    op.create_unique_constraint(op.f('shipments_tracking_number_key'), 'shipments', ['tracking_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('sessions_token_hash_key'), 'sessions', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.create_unique_constraint(op.f('products_slug_key'), 'products', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=False)
    op.create_unique_constraint(op.f('product_variants_sku_key'), 'product_variants', ['sku'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_pages_slug'), table_name='pages')
    op.create_index(op.f('ix_pages_slug'), 'pages', ['slug'], unique=False)
    op.create_unique_constraint(op.f('pages_slug_key'), 'pages', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_orders_number'), table_name='orders')
    op.create_index(op.f('ix_orders_number'), 'orders', ['number'], unique=False)
    op.create_unique_constraint(op.f('orders_number_key'), 'orders', ['number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_domain_events_aggregate_type'), table_name='domain_events')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_unique_constraint(op.f('categories_slug_key'), 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
